# Pour tester en local : docker compose up --build  ->  http://localhost:8081
# (port 8081 de la machine -> port 8080 du conteneur ; sur EC2 on utilisera 80 -> 8080)
services:
  taskflow:
    build: .
    image: taskflow:local
    container_name: taskflow
    ports:
      - "8081:8080"
    volumes:
      - taskdata:/app/data
    restart: unless-stopped

volumes:
  taskdata:
